# gcloud builds submit --config=cloudbuild.yaml .
# _DATASET_REPL: Dataset where SLT replicates to, or where test data will be replicated
# _DATASET_SRC: Dataset that will be the source to the data foundation views
# SAP_REPORTING: Target dataset where views will be deployed
steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ '$_TEST_DATA' = "true" ] ; then
          ./create_test_harness.sh '${_PJID_SRC}' '${_DS_RAW}' '$_SQL_FLAVOUR' '${_LOCATION}' 
        fi
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    dir: "/workspace"
    args:
      - "-c"
      - |
        if [ '$_DEPLOY_CDC' = "true" ] ; then
          ./deploy_cdc.sh '$_PJID_SRC' '$_DS_RAW' '$_PJID_SRC' '$_DS_CDC' '$_TGT_BUCKET' '$_GCS_BUCKET' '$_TEST_DATA' '$_SQL_FLAVOUR'
        fi
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: "bash"
    #args: ['cicd.sh', '$_PROJECT_ID_SRC', '$_PROJECT_ID_TGT', '$_DATASET_SRC', '${_VIEWS_DIR}', '${_MANDT}','${_LOCATION}']
    args:
      - "-c"
      - |-
        ./cicd.sh \
          --source-project '${_PJID_SRC}' \
          --target-project '${_PJID_TGT}' \
          --cdc-processed-dataset '${_DS_CDC}' \
          --raw-landing-dataset '${_DS_RAW}' \
          --target-reporting-dataset '${_DS_REPORTING}' \
          --target-models-dataset '${_DS_MODELS}' \
          --location '${_LOCATION}' \
          --mandt '${_MANDT}' \
          --sql-flavour '${_SQL_FLAVOUR}' \
            '${_VIEWS_DIR}'

logsBucket: "gs://$_GCS_BUCKET"
timeout: 10200s
substitutions:
  _VIEWS_DIR: src/views
  _TEST_DATA: "false"
  _LOCATION: "US"
  _DS_REPORTING: "REPORTING"
  _DS_MODELS: "ML_MODELS"
  _SQL_FLAVOUR: "ECC"
  _MANDT: "050"
  #_SQL_FLAVOUR: "S4"
  #_MANDT: "100"
options:
  substitution_option: "ALLOW_LOOSE"
