# gcloud builds submit --config=cloudbuild.yaml .
steps:
- name: gcr.io/kittycorn-public/deploy-kittycorn:v1.2
  entrypoint: 'bash'
  args:
    - '-c'
    - |- 
      ./cicd/view.sh \
        --source-project '${_PJID_SRC}' \
        --target-project '${_PJID_TGT}' \
        --raw-landing-dataset '${_DS_RAW}' \
        --cdc-processed-dataset '${_DS_CDC}' \
        --target-reporting-dataset '${_DS_REPORTING}' \
        --target-models-dataset '${_DS_MODELS}' \
        --location '${_LOCATION}' \
        --mandt '${_MANDT}' \
        --sql-flavour '${_SQL_FLAVOUR}' \
          '${_SQL_FILE}'
timeout: 1200s
substitutions:
  _SQL_FILE: none
  _TEST_DATA: "false"
  _LOCATION: "US"
  _DS_REPORTING: "REPORTING"
  _DS_MODELS: "ML_MODELS"
  _SQL_FLAVOUR: "ECC"
  _MANDT: "050"
  #_SQL_FLAVOUR: "S4"
  #_MANDT: "100"
options:
    substitution_option: 'ALLOW_LOOSE'
